serverInfo:
  name: "Aces ARKA-ARKB Channel Service"
  description: "ACES ARKA to ARKB Channel service for value transfers"
  instructions: >
    After this contract is executed, any ARKA sent to depositArkaAddress will be exchanged for ARKB and
    sent directly to the given recipientArkbAddress less service fees.
  version: "1.1.0"
  websiteUrl: "https://arkaces.com"
  # Exchange rate is a static value because ARKB will not likely have an active market. Set this value to the amount of ARKB you will receive for each ARKA. The default provides 1 ARKB for each 1 ARKA received.
  arkbPerArka: "1"
  # Flat fee label (actual fee charged is is fees.arkaFlatFee property
  flatFee: "1 ARK"
  # Percent fee label (actual percent fee charged is in fees.arkaPercentFee property
  percentFee: "1.00%"

  # Uncomment below to override shown capacity, by default the capacity will be set to the amount in the service address
#  capacities:
#    -
#      value: "100000000.00"
#      unit: "ARKB"
#      displayValue: "100000000 ARKB"

  inputSchema: >
    {
      "type": "object",
      "properties": {
        "recipientArkbAddress": {
          "type": "string",
          "title": "Recipient ARKB Address",
          "description": "Enter recipient ARKB address to transfer funds to."
        }
      },
      "required": [
        "recipientArkbAddress"
      ]
    }
  outputSchema: >
    {
      "type": "object",
      "properties": {
        "depositArkaAddress": {
          "type": "string"
        },
        "recipientArkbAddress": {
          "type": "string"
        },
        "transfers": {
          "type": "array",
          "properties": {
            "arkAmount": {
              "type": "string"
            },
            "arkbPerArka": {
              "type": "string"
            },
            "arkaFlatFee": {
              "type": "string"
            },
            "arkaPercentFee": {
              "type": "string"
            },
            "arkaTotalFee": {
              "type": "string"
            },
            "arkbSendAmount": {
              "type": "string"
            },
            "arkbTransactionId": {
              "type": "string"
            },
            "createdAt": {
              "type": "string"
            }
          }
        }
      }
    }

arkaNetworkConfigPath: "ark_network_config/devnet.yml"
arkbNetworkConfigPath: "ark_network_config/devnet.yml"

arkaUnit: "DARK"
arkbUnit: "DARK"

fees:
  arkaFlatFee: 1
  arkaPercentFee: 1

arkbPerArka: 1

server:
  port: 9191

spring:
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://localhost:5432/arka_arkb_channel_service_db"
    username: "postgres"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: "validate"

arkaListener:
  url: http://localhost:9091

arkaEventCallbackUrl: http://localhost:9191/arkaEvents

serviceArkbAccount:
  address: change_me
  passphrase: change_me